version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: skill-match-auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  auth-service:
#    build:
#      context: ./auth-service
#    container_name: auth-service
#    ports:
#      - "8081:8081"
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: authdb
#    depends_on:
#      - postgres
#
#  api-gateway:
#    build:
#      context: ./api-gateway
#    container_name: api-gateway
#    ports:
#      - "8080:8080"
#    depends_on:
#      - auth-service

volumes:
  pgdata:
